services:
  spark-master:
    image: custom-spark:4.0.1
    container_name: spark-master
    hostname: spark-master
    ports:
      - "7077:7077"
      - "8083:8080"
    environment:
      - SPARK_ROLE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
      - shared-network
    volumes:
      - ./logs/log4j2.properties:/opt/spark/conf/log4j2.properties:ro
      - ./notebooks:/notebooks
      - ../trino/hive-metastore/hive-site.xml:/opt/spark/conf/hive-site.xml:ro

  spark-worker-1:
    image: custom-spark:4.0.1
    container_name: spark-worker-1
    hostname: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
      - shared-network
    volumes:
      - ./logs/log4j2.properties:/opt/spark/conf/log4j2.properties:ro
      - ./notebooks:/notebooks
      - ../trino/hive-metastore/hive-site.xml:/opt/spark/conf/hive-site.xml:ro

  spark-worker-2:
    image: custom-spark:4.0.1
    container_name: spark-worker-2
    hostname: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - SPARK_ROLE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    networks:
      - spark-network
      - shared-network
    volumes:
      - ./logs/log4j2.properties:/opt/spark/conf/log4j2.properties:ro
      - ./notebooks:/notebooks
      - ../trino/hive-metastore/hive-site.xml:/opt/spark/conf/hive-site.xml:ro
      
  spark-history-server:
    image: custom-spark:4.0.1
    container_name: spark-history-server
    hostname: spark-history-server
    depends_on:
      - spark-master
    ports:
      - "18080:18080"
    environment:
      - SPARK_ROLE=history
    networks:
      - spark-network
      - shared-network
  # zepellin:
  #   image: custom-spark:4.0.1
  #   container_name: zeppelin_server
  #   ports:
  #     - "8085:8080"  # Zeppelin Web UI
  #   networks:
  #     - spark-network
  #     - shared-network
  #   environment:
  #     - SPARK_ROLE=zeppelin
  #     - USE_HADOOP=false
  #     - ZEPPELIN_ADDR=0.0.0.0
  #   volumes:
  #     - ./logs/log4j2.properties:/opt/spark/conf/log4j2.properties:ro
  #     - ./zep_notebooks:/opt/zeppelin/notebook
  #     - ../trino/hive-metastore/hive-site.xml:/opt/spark/conf/hive-site.xml:ro
  #   command: ["zeppelin", "/opt/zeppelin/bin/zeppelin.sh"]


networks:
  spark-network:
    driver: bridge
    name: spark-network
  shared-network:
    external: true
